deploy:
  provider: lambda
  function_name: "hello-world-function"
  region: "us-west-2"
  role: "arn:aws:iam::123689029439:role/hello-world-function_lambda_function"
  runtime: "nodejs4.3"
  handler_name: "handle"
  publish: true

install:
  - yarn
  - yarn compile